baseURL = "http://5wop5l6jtsnpu4srabepyb43qxznptu3gto2usgjmf6dd3hbjcbpewad.onion"
theme = "risotto"
title = "Plaintext Audits"
author = "Plaintext Frens"
copyright = ""
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "Plaintext Audits"
description = "Comfy Code"
logo = "images/rice.svg"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true
